# Generated by Django 5.2.4 on 2025-07-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['sender'], name='core_emaill_sender_16063a_idx'), models.Index(fields=['recipient'], name='core_emaill_recipie_419f42_idx'), models.Index(fields=['received_at'], name='core_emaill_receive_910f30_idx'), models.Index(fields=['processed'], name='core_emaill_process_dd8d61_idx')],
            },
        ),
    ]
