# Generated by Django 5.2.7 on 2025-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_merge_0002_userprofile_custom_footer_html_emailfooter_0002_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spf_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time SPF record was checked', null=True, verbose_name='SPF Last Checked'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spf_missing_includes',
            field=models.JSONField(blank=True, default=list, help_text='List of missing required SPF includes', verbose_name='SPF Missing Includes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spf_record',
            field=models.TextField(blank=True, help_text="The SPF record found for the user's domain", verbose_name='SPF Record'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spf_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has a valid SPF record', verbose_name='SPF Verified'),
        ),
    ]
