# Generated by Django 5.2.7 on 2026-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_userprofile_address_line1_userprofile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name to use in email From header', max_length=255, verbose_name='Full Name'),
        ),
    ]
