# Generated by Django 5.2.7 on 2026-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_add_full_name_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_bcc_enabled',
            field=models.BooleanField(default=True, help_text='Automatically BCC this email address whenever a new email is sent', verbose_name='Auto BCC Enabled'),
        ),
    ]
