# Generated by Django 5.2.7 on 2026-01-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_add_auto_bcc_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ipv4',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4 address at last login', null=True, protocol='IPv4', verbose_name='Last login IPv4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ipv6',
            field=models.GenericIPAddressField(blank=True, help_text='IPv6 address at last login', null=True, protocol='IPv6', verbose_name='Last login IPv6'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ipv4',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4 address at registration', null=True, protocol='IPv4', verbose_name='Registration IPv4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ipv6',
            field=models.GenericIPAddressField(blank=True, help_text='IPv6 address at registration', null=True, protocol='IPv6', verbose_name='Registration IPv6'),
        ),
    ]
