from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('pricing/', views.pricing, name='pricing'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send-contact/', views.send_contact_redirect, name='send-contact'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('settings/', views.account_settings, name='settings'),
    path('promo-verification/', views.promo_verification, name='promo_verification'),
    # Feature pages
    path('features/drip-campaigns/', views.feature_drip_campaigns, name='feature_drip_campaigns'),
    path('features/email-scheduling/', views.feature_email_scheduling, name='feature_email_scheduling'),
    path('features/analytics/', views.feature_analytics, name='feature_analytics'),
    path('features/subscriber-management/', views.feature_subscriber_management, name='feature_subscriber_management'),
    path('features/email-templates/', views.feature_email_templates, name='feature_email_templates'),
    # Resource pages
    path('resources/documentation/', views.resource_documentation, name='resource_documentation'),
    # Documentation subpages
    path('resources/documentation/getting-started/', views.docs_getting_started, name='docs_getting_started'),
    path('resources/documentation/campaigns/', views.docs_campaigns, name='docs_campaigns'),
    path('resources/documentation/subscribers/', views.docs_subscribers, name='docs_subscribers'),
    path('resources/documentation/templates/', views.docs_templates, name='docs_templates'),
    path('resources/documentation/analytics/', views.docs_analytics, name='docs_analytics'),
    path('resources/documentation/ai-features/', views.docs_ai_features, name='docs_ai_features'),
    path('resources/documentation/smtp-server/', views.docs_smtp_server, name='docs_smtp_server'),
    path('resources/documentation/deployment/', views.docs_deployment, name='docs_deployment'),
    path('resources/documentation/deployment/prerequisites/', views.docs_deployment_prerequisites, name='docs_deployment_prerequisites'),
    path('resources/documentation/deployment/installation/', views.docs_deployment_installation, name='docs_deployment_installation'),
    path('resources/documentation/deployment/configuration/', views.docs_deployment_configuration, name='docs_deployment_configuration'),
    path('resources/documentation/deployment/production/', views.docs_deployment_production, name='docs_deployment_production'),
    path('resources/documentation/deployment/troubleshooting/', views.docs_deployment_troubleshooting, name='docs_deployment_troubleshooting'),
    path('resources/tutorials/', views.resource_tutorials, name='resource_tutorials'),
    # Tutorial detail pages
    path('resources/tutorials/quick-start/', views.tutorial_quick_start, name='tutorial_quick_start'),
    path('resources/tutorials/dashboard-overview/', views.tutorial_dashboard_overview, name='tutorial_dashboard_overview'),
    path('resources/tutorials/account-setup/', views.tutorial_account_setup, name='tutorial_account_setup'),
    path('resources/tutorials/creating-campaign/', views.tutorial_creating_campaign, name='tutorial_creating_campaign'),
    path('resources/tutorials/drip-campaigns/', views.tutorial_drip_campaigns, name='tutorial_drip_campaigns'),
    path('resources/tutorials/scheduling-campaigns/', views.tutorial_scheduling_campaigns, name='tutorial_scheduling_campaigns'),
    path('resources/tutorials/importing-subscribers/', views.tutorial_importing_subscribers, name='tutorial_importing_subscribers'),
    path('resources/tutorials/managing-lists/', views.tutorial_managing_lists, name='tutorial_managing_lists'),
    path('resources/tutorials/subscriber-segmentation/', views.tutorial_subscriber_segmentation, name='tutorial_subscriber_segmentation'),
    path('resources/tutorials/email-editor/', views.tutorial_email_editor, name='tutorial_email_editor'),
    path('resources/tutorials/reusable-templates/', views.tutorial_reusable_templates, name='tutorial_reusable_templates'),
    path('resources/tutorials/design-best-practices/', views.tutorial_design_best_practices, name='tutorial_design_best_practices'),
    path('resources/tutorials/ai-setup/', views.tutorial_ai_setup, name='tutorial_ai_setup'),
    path('resources/tutorials/ai-generation/', views.tutorial_ai_generation, name='tutorial_ai_generation'),
    path('resources/tutorials/ai-optimization/', views.tutorial_ai_optimization, name='tutorial_ai_optimization'),
    path('resources/tutorials/email-analytics/', views.tutorial_email_analytics, name='tutorial_email_analytics'),
    path('resources/tutorials/performance-dashboard/', views.tutorial_performance_dashboard, name='tutorial_performance_dashboard'),
    path('resources/tutorials/data-optimization/', views.tutorial_data_optimization, name='tutorial_data_optimization'),
    path('resources/tutorials/smtp-setup/', views.tutorial_smtp_setup, name='tutorial_smtp_setup'),
    path('resources/tutorials/deployment/', views.tutorial_deployment, name='tutorial_deployment'),
    path('resources/tutorials/api-integration/', views.tutorial_api_integration, name='tutorial_api_integration'),
    path('resources/api-reference/', views.resource_api_reference, name='resource_api_reference'),
    path('resources/community/', views.resource_community, name='resource_community'),
    # Community resource pages
    path('resources/community/user-forum/', views.community_user_forum, name='community_user_forum'),
    path('resources/community/feature-requests/', views.community_feature_requests, name='community_feature_requests'),
    path('resources/community/success-stories/', views.community_success_stories, name='community_success_stories'),
    path('resources/community/social/', views.community_social, name='community_social'),
    # Blog
    path('resources/blog/', views.blog_index, name='blog_index'),
    path('resources/blog/forum/', views.blog_forum, name='blog_forum'),
    path('resources/blog/<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]