# Generated by Django 5.0.2 on 2025-05-13 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Sent Count')),
                ('open_count', models.IntegerField(default=0, verbose_name='Open Count')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('subscriber_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='subscribers.list', verbose_name='Subscriber List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('body_html', models.TextField(verbose_name='HTML Body')),
                ('body_text', models.TextField(verbose_name='Text Body')),
                ('wait_time', models.IntegerField(default=1, help_text='Time to wait before sending this email', verbose_name='Wait Time')),
                ('wait_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=5, verbose_name='Wait Unit')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaigns.campaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_email', models.EmailField(max_length=254, verbose_name='Subscriber Email')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed')], max_length=20, verbose_name='Event Type')),
                ('link_clicked', models.URLField(blank=True, null=True, verbose_name='Link Clicked')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.email', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
