# Generated by Django 4.2.21 on 2025-07-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_userprofile_custom_footer_html_emailfooter'),
        ('campaigns', '0002_alter_campaign_subscriber_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.emailfooter', verbose_name='Footer'),
        ),
    ]
