# Generated by Django 4.2.21 on 2025-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_email_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='wait_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=7, verbose_name='Wait Unit'),
        ),
    ]
