# Generated by Django 5.2.4 on 2025-11-13 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_emailsendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_subject', models.CharField(blank=True, max_length=200, verbose_name='Generated Subject')),
                ('generated_body_html', models.TextField(blank=True, verbose_name='Generated Body HTML')),
                ('generation_prompt', models.TextField(blank=True, help_text='The prompt used to generate content', verbose_name='Generation Prompt')),
                ('generation_model', models.CharField(blank=True, default='gpt-3.5-turbo', max_length=50, verbose_name='Generation Model')),
                ('topics_json', models.JSONField(blank=True, default=list, help_text='Extracted topics and keywords', verbose_name='Topics')),
                ('dominant_topics', models.JSONField(blank=True, default=list, help_text='Dominant topic for this email', verbose_name='Dominant Topics')),
                ('topic_analysis_count', models.IntegerField(default=0, help_text='Number of emails used in topic analysis', verbose_name='Emails Analyzed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='campaigns.email', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email AI Analysis',
                'verbose_name_plural': 'Email AI Analyses',
            },
        ),
    ]
