# Generated by Django 5.2.7 on 2026-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='wait_unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=7, verbose_name='Wait Unit'),
        ),
    ]
