# Generated by Django 5.2.7 on 2026-02-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_email_wait_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bounce_count',
            field=models.IntegerField(default=0, verbose_name='Bounce Count'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='complaint_count',
            field=models.IntegerField(default=0, verbose_name='Complaint Count'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe_count',
            field=models.IntegerField(default=0, verbose_name='Unsubscribe Count'),
        ),
    ]
