# Generated by Django 5.2.7 on 2026-01-11 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0007_alter_campaign_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP')], default='gmail', max_length=20, verbose_name='Provider')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Token Expiry')),
                ('imap_host', models.CharField(blank=True, max_length=255, verbose_name='IMAP Host')),
                ('imap_port', models.IntegerField(blank=True, null=True, verbose_name='IMAP Port')),
                ('imap_username', models.CharField(blank=True, max_length=255, verbose_name='IMAP Username')),
                ('imap_password', models.TextField(blank=True, verbose_name='IMAP Password')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='Use SSL')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync Enabled')),
                ('provider_settings', models.JSONField(blank=True, default=dict, verbose_name='Provider Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_credentials', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Credential',
                'verbose_name_plural': 'Email Credentials',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP')], default='gmail', max_length=20, verbose_name='Provider')),
                ('provider_message_id', models.CharField(db_index=True, max_length=255, verbose_name='Provider Message ID')),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Thread ID')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Subject')),
                ('from_email', models.EmailField(max_length=254, verbose_name='From Email')),
                ('to_emails', models.TextField(help_text='Comma-separated email addresses', verbose_name='To Emails')),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated email addresses', verbose_name='CC Emails')),
                ('bcc_emails', models.TextField(blank=True, help_text='Comma-separated email addresses', verbose_name='BCC Emails')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Sender Email')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Reply To')),
                ('body_text', models.TextField(blank=True, verbose_name='Body Text')),
                ('body_html', models.TextField(blank=True, verbose_name='Body HTML')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='Received At')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched At')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='Provider Data')),
                ('campaign_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='campaigns.email', verbose_name='Campaign Email')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='gmail.emailcredential', verbose_name='Credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailcredential',
            index=models.Index(fields=['user', 'provider', 'is_active'], name='gmail_email_user_id_e25adc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailcredential',
            unique_together={('user', 'provider', 'email_address')},
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user', 'provider', '-received_at'], name='gmail_email_user_id_11c994_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['credential', '-received_at'], name='gmail_email_credent_fb22b7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['processed', '-received_at'], name='gmail_email_process_cd720a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['thread_id'], name='gmail_email_thread__9c67de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('credential', 'provider_message_id')},
        ),
    ]
